### ISSUE TITLE
CPs sometimes fail to load for client

### ISSUE THREAD

**Issue by zrisher** [stackcollision/GardenConquest#102]
We should make these more reliable, retry if not received the first time around.

**Comment by zrisher** [comment]
Nvm, this is not a reliability issue, looks like we don't send the settings so well sometimes:

```
[2015-07-17 02:36:06,227][ERROR][Conquest Core][ResponseProcessor][incomming][][]Exception occured: System.IO.EndOfStreamException: Stream does not have enough size
   at VRage.ByteStream.CheckCapacity(Int64 minimumSize)
   at VRage.ByteStream.ReadByte()
   at GardenConquest.Extensions.ByteConverterExtension.getUShort(ByteStream stream)
   at GardenConquest.Records.HullRuleSet.deserialize(ByteStream stream)
   at GardenConquest.Messaging.SettingsResponse.deserialize(ByteStream stream)
   at GardenConquest.Messaging.BaseResponse.messageFromBytes(Byte[] buffer)
   at GardenConquest.Messaging.ResponseProcessor.incomming(Byte[] buffer)
[2015-07-17 02:36:19,558][ERROR][Conquest Core][Command Processor][handleChatCommand][][]Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at GardenConquest.Core.CommandProcessor.helpCPsText()
   at GardenConquest.Core.CommandProcessor.handleChatCommand(String messageText, Boolean& sendToOthers)
```

**Comment by zrisher** [comment]
Whoops, this is because the client and server version aren't in sync! Since we just pushed the patch that adds ShoulBeStation to the hullruleset, client expects to deserialize it but server isn't sending.
