### ISSUE TITLE
Exception in Core_Server.eventCleanupViolation

### ISSUE THREAD

**Issue by zrisher** [stackcollision/GardenConquest#104]
This was spammed every 100 frames for 2 hours and 20 minutes on the same grid:

```
[2015-07-18 03:41:14,420][ERROR][145296933244176754][GridEnforcer][UpdateBeforeSimulation100][][]Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at GardenConquest.Core.Core_Server.eventCleanupViolation(GridEnforcer ge, List`1 violations)
   at GardenConquest.Blocks.GridEnforcer.notifyViolations()
   at GardenConquest.Blocks.GridEnforcer.UpdateBeforeSimulation100()
```

**Comment by zrisher** [comment]
Still getting this occasionally.

**Comment by MrZSFG** [comment]
this still happen or you fix it compltely now

**Comment by zrisher** [comment]
I'm not sure, but I'll be reorging a lot of the code in preparation for communication with conceal, so we can close this.
