### ISSUE TITLE
MergeBlock entity duplication

### ISSUE THREAD

**Issue by stackcollision** [stackcollision/GardenConquest#27]
Occurred after lots of copy-pasting

2015-05-13 19:55:00.045 - Thread:   8 ->  ERROR while adding cube Merge Block: System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Sandbox.Game.Entities.MyEntity.set_EntityId(Int64 value)
   at Sandbox.Game.Entities.MyCubeBlock.Init(MyObjectBuilder_CubeBlock builder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyTerminalBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Blocks.MyShipMergeBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MySlimBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid, MyCubeBlock fatBlock)
   at Sandbox.Game.Entities.MyCubeGrid.AddCubeBlock(MyObjectBuilder_CubeBlock objectBuilder, Boolean testMerge, MyCubeBlockDefinition blockDefinition)
   at Sandbox.Game.Entities.MyCubeGrid.AddBlock(MyObjectBuilder_CubeBlock objectBuilder, Boolean testMerge)

**Comment by zrisher** [comment]
I think we can close this, there's no evidence it's even related to GC.
