### ISSUE TITLE
Errors in onSend(buffer)

### ISSUE THREAD

**Issue by zrisher** [stackcollision/GardenConquest#65]
```
2015-06-02 11:12:09,062][DEBUG][152749197959367651][GridEnforcer][currentViolations][][]finished
[2015-06-02 11:12:09,062][DEBUG][152749197959367651][GridEnforcer][updateCleanup][][]start
[2015-06-02 11:12:27,254][DEBUG][Conquest Core][RequestProcessor][incomming][][]Got message of size 10
[2015-06-02 11:12:27,254][DEBUG][Conquest Core][RequestProcessor][processCPGPSRequest][][]
[2015-06-02 11:12:27,254][DEBUG][Conquest Core][RequestProcessor][send][][]Sent packet of 256 bytes
[2015-06-02 11:12:27,254][ERROR][Conquest Core][RequestProcessor][send][][]Error in onSend(buffer) System.NullReferenceException: Object reference not set to an instance of an object.
   at GardenConquest.Messaging.RequestProcessor.send(BaseResponse msg)
```

```
[2015-06-02 11:23:47,968][DEBUG][Conquest Core][Server][roundEnd][][]Timer triggered
[2015-06-02 11:23:47,968][DEBUG][Conquest Core][Server][roundEnd][][]Processing control point CP Alpha
[2015-06-02 11:23:47,968][DEBUG][Conquest Core][Server][roundEnd][][]Found 1 grids in CP SOI
[2015-06-02 11:23:47,968][DEBUG][215789532299643062][GridOwner][reevaluateOwnership][][]old type: FACTION, player: 144115188075855884, faction: 190949050489601148, fleet: 190949050489601148
[2015-06-02 11:23:47,968][DEBUG][215789532299643062][GridOwner][reevaluateOwnership][][]no change
[2015-06-02 11:23:47,968][DEBUG][Conquest Core][Server][groupFactionGrids][][]Grid KDS Armored Needle belongs to fleet 190949050489601148
[2015-06-02 11:23:47,968][DEBUG][Conquest Core][Server][roundEnd][][]After aggregation there are 1 factions present
[2015-06-02 11:23:47,968][DEBUG][Conquest Core][Server][roundEnd][][]Grids for faction 190949050489601148
[2015-06-02 11:23:47,968][DEBUG][Conquest Core][Server][roundEnd][][]   
[2015-06-02 11:23:47,968][DEBUG][Conquest Core][Server][roundEnd][][]Faction with most grids: 190949050489601148
[2015-06-02 11:23:47,968][DEBUG][Conquest Core][Server][roundEnd][][]Number of (weighted) grids: 1
[2015-06-02 11:23:47,968][DEBUG][Conquest Core][Server][roundEnd][][]Tie? False
[2015-06-02 11:23:47,968][DEBUG][Conquest Core][Server][roundEnd][][]Sorting list of grids
[2015-06-02 11:23:47,968][DEBUG][Conquest Core][Server][roundEnd][][]Looking for valid container
[2015-06-02 11:23:47,969][DEBUG][Conquest Core][Server][roundEnd][][]Found a ship to put tokens in
[2015-06-02 11:23:47,969][DEBUG][Conquest Core][StateTracker][saveState][][]Write finished
[2015-06-02 11:23:47,969][DEBUG][Conquest Core][Server][roundEnd][][]Sending message
[2015-06-02 11:23:47,969][DEBUG][Conquest Core][RequestProcessor][send][][]Sent packet of 256 bytes
[2015-06-02 11:23:47,969][ERROR][Conquest Core][RequestProcessor][send][][]Error in onSend(buffer) System.NullReferenceException: Object reference not set to an instance of an object.
   at GardenConquest.Messaging.RequestProcessor.send(BaseResponse msg)
[2015-06-02 11:23:47,969][DEBUG][Conquest Core][RequestProcessor][send][][]Sent packet of 256 bytes
[2015-06-02 11:23:47,969][ERROR][Conquest Core][RequestProcessor][send][][]Error in onSend(buffer) System.NullReferenceException: Object reference not set to an instance of an object.
   at GardenConquest.Messaging.RequestProcessor.send(BaseResponse msg)
```

**Comment by zrisher** [comment]
Closed via #71
