### ISSUE TITLE
Error getting fleet

### ISSUE THREAD

**Issue by zrisher** [stackcollision/GardenConquest#66]
```
[2015-06-02 11:09:41,370][DEBUG][184091265522161130][GridEnforcer][UpdateBeforeSimulation100][][]checking cleanup state due to flag
[2015-06-02 11:09:41,370][DEBUG][184091265522161130][GridOwner][reevaluateOwnership][][]old type: UNOWNED, player: 0, faction: 0, fleet: 0
[2015-06-02 11:09:41,370][DEBUG][184091265522161130][GridOwner][effectOwnershipChanged][][]Changing ownership to: FACTION, player: 144115188075856030, faction: 166410726898267045
[2015-06-02 11:09:41,370][TRACE][Static][FactionFleet][updateSupportRemoved][][]unsupportedGrids.count 0
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]Fleet 0 count(sup+unsup)/max : 
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]  Class UNCLASSIFIED - 58 / 0
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]  Unsupported: 
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    193796433417150221 - jodys min bob
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    157118532788973969 - jodys miner
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    162866634225199573 - jodys bob
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    207755108294203453 - jodys pod 1
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    206751902792076028 - chicken drill ship
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    180199112565299053 - Jodys pod 2
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    185254494928460135 - xTcR main small mining vesel. (DON'T DELETE PLEASE!!!)
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    164804084644656926 - lordmetal Platform 1697
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    156508604731674221 - trashy
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    189002496650473536 - Bolshoy Drel 2.0
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    188301045933790107 - eroit Small Ship 7772
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    206397614032198097 - mikkel Small Ship 4290
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    213619069983229887 - wuffleton Platform 8248
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    194183029289464623 - SEG scrapping ship. (Do not delete.)
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    183723027481060805 - driox Small Ship 1205
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    183722971477807076 - driox Small Ship 1384
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    187819696892781596 - 2 head earth breaker drill
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    176798389166819211 - Small Ship 9211
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    192811847026553808 - Small Ship 6683
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    179527645739288096 - chicken Small Ship 6112
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    158901873601932372 - KDS Welder
[2015-06-02 11:09:41,370][DEBUG][Static][FactionFleet][remove][][]    200750193625228295 - Platform 4982
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    172295216664314531 - pappi Small Ship 5998
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    174722631630960019 - pappi Small Ship 3741
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    203837887001959599 - Small Ship 5402
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    152521717059643727 - R1ot Scatter auto canon fighter
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    212879341595802061 - Small Ship 3692
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    205220321263158881 - Utility Ship
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    156572829869968796 - EarthMiner
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    151757670036390046 - chicken welder
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    153906923878778232 - chicken Small Ship 7848
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    199589018703054337 - S.C.V. Mk.1
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    167603152567509113 - macro Small Ship 2638
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    202500988318073464 - KDS Probe
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    155893995557635170 - Turret Drone 1
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    170283983251155953 - Small Ship 5953
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    177969539071025462 - godly Small Ship 8869
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    201753896567860534 - Respawnship
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    146433614390405439 - Small Ship 9796
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    204996613066435053 - CYO.-NCM- dragon breath
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    209919560172774784 - Small Ship 4784
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    213032559742545562 - Wazar Battleship Class II
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    175607417745456299 - drok Small Ship 7673
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    170077175072542374 - Small Ship 2863
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    150443313556498887 - Small Ship 4520
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    167360025701138844 - Metal Eater
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    152983752127067131 - laserbobby
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    156194593627560993 - Large Ship 2904
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    214136357506823321 - Platform 3321
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    172692157720165953 - gidiens Small Ship 1445
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    197916542249577583 - KDS Swarmer
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    155901459425759949 - KDS Multirail Corvette
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    144503905480977044 - Small Ship 6567
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    189680559389488642 - CYO.NCM-arc
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    214784288653009010 - Large Ship 9010
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    180947366686380163 - Platform 163
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    183953778489298524 - Small Ship 8524
[2015-06-02 11:09:41,371][DEBUG][Static][FactionFleet][remove][][]    151372969348517471 - Er1ot mother ship
[2015-06-02 11:09:41,371][ERROR][184091265522161130][GridOwner][effectOwnershipChanged][][]Failed to get new fleet for 166410726898267045
[2015-06-02 11:09:41,371][DEBUG][184091265522161130][GridEnforcer][reevaluateOwnership][][]owner changed
[2015-06-02 11:09:41,371][DEBUG][184091265522161130][GridEnforcer][UpdateBeforeSimulation100][][]Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at GardenConquest.Blocks.GridEnforcer.currentViolations()
   at GardenConquest.Blocks.GridEnforcer.UpdateBeforeSimulation100()
```

**Comment by zrisher** [comment]
This seems to be fixed, haven't received in a week.
